SELECT s.indexed_columns, GROUP_CONCAT(INDEX_NAME) as indexes
FROM (
    SELECT INDEX_NAME, GROUP_CONCAT(CONCAT (TABLE_NAME,'.',COLUMN_NAME) ORDER BY CONCAT (SEQ_IN_INDEX,'COLUMN_NAME')) as indexed_columns
   FROM INFORMATION_SCHEMA.STATISTICS
   GROUP BY INDEX_NAME
)as s
GROUP BY indexed_columns
HAVING COUNT(*) > 1;